#!/bin/bash
# Test script for swarm improvements

echo "======================================"
echo "SWARM MODE TEST SCRIPT"
echo "======================================"
echo ""
echo "This script will:"
echo "1. Pull latest changes on the Edison server"
echo "2. Restart Edison services"
echo "3. Show you what to test"
echo ""
echo "Run this on your Edison server:"
echo ""
echo "cd /opt/edison && sudo -u edison git pull origin main"
echo "sudo systemctl restart edison-core edison-web"
echo "sleep 5"
echo "sudo journalctl -u edison-core -f"
echo ""
echo "======================================"
echo "MANUAL TESTING STEPS"
echo "======================================"
echo ""
echo "1. Open Edison web UI in browser"
echo ""
echo "2. Select SWARM mode (🐝 icon)"
echo ""
echo "3. Ask a complex question like:"
echo "   - 'Explain how neural networks work and provide a simple Python implementation'"
echo "   - 'Design a REST API for a todo app with proper architecture'"
echo "   - 'Create a website layout for a fitness brand called Release the Beast'"
echo ""
echo "4. Wait for response (will take longer than normal - 6 agent calls + synthesis)"
echo ""
echo "5. Check the response:"
echo "   ✅ Should see '🐝 Agent Discussion (6 messages)' collapsible section"
echo "   ✅ Click to expand and see all 6 agent responses"
echo "   ✅ Each agent should show their icon, name, and model"
echo "   ✅ Should see Round 1 and Round 2 responses"
echo "   ✅ Final synthesized response should be coherent, not looping"
echo ""
echo "6. Check the logs (journalctl output):"
echo "   ✅ Should see '🐝 Swarm mode activated'"
echo "   ✅ Should see '🐝 Round 1: Initial agent perspectives'"
echo "   ✅ Should see agent icons: 🔍 🧠 ⚙️"
echo "   ✅ Should see model names: (Qwen 14B (Fast)) and (Qwen 72B (Deep))"
echo "   ✅ Should see '🐝 Round 2: Agent collaboration'"
echo "   ✅ Should see GPU utilization: 🎮 GPU 0: X.XXGB allocated"
echo ""
echo "======================================"
echo "EXPECTED BEHAVIOR"
echo "======================================"
echo ""
echo "Agent Roles:"
echo "  🔍 Researcher (14B) - Gathers facts and context"
echo "  🧠 Analyst (72B)    - Provides deep strategic analysis"
echo "  ⚙️ Implementer (14B) - Suggests practical implementation"
echo ""
echo "Conversation Flow:"
echo "  Round 1: Each agent gives initial perspective (3 messages)"
echo "  Round 2: Each agent responds to others (3 more messages)"
echo "  Total: 6 agent messages + 1 synthesized response"
echo ""
echo "UI Display:"
echo "  - Main response shows synthesis"
echo "  - Collapsible panel shows full agent conversation"
echo "  - Each message labeled with agent name/icon/model"
echo ""
echo "GPU Usage:"
echo "  - Logs show memory allocated on each GPU during inference"
echo "  - Should see CUDA0, CUDA1, CUDA2 usage"
echo ""
echo "======================================"
echo "TROUBLESHOOTING"
echo "======================================"
echo ""
echo "If agent discussion doesn't show:"
echo "  - Clear browser cache (Ctrl+Shift+R)"
echo "  - Check browser console for errors (F12)"
echo ""
echo "If responses are still looping:"
echo "  - Check that services restarted successfully"
echo "  - Verify git pull succeeded"
echo ""
echo "If GPU usage not showing:"
echo "  - Check logs with: sudo journalctl -u edison-core -n 100"
echo ""
echo "======================================"
